name: 17wanxiaoCheckin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22 * * *    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
        
    - name: Checkin
      run: |
	python3 C189Checkin.py <<EOF
	${{ secrets.TEXT}}
	${{ secrets.ADDRESS}}
	${{ secrets.ADDTEXT}}
	${{ secrets.DEPTID}}
	${{ secrets.USERID}}
	${{ secrets.STUNUM}}
	${{ secrets.USERNAME}}
	${{ secrets.PHONENUM}}
	${{ secrets.EMERGENCY}}
	${{ secrets.EMERGENCYPHONE}}	
	EOF
