name: 17wanxiaoCheckin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22 * * *    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
      	text = '${{ secrets.TEXT}}'
	address = '${{ secrets.ADDRESS}}'
	addtxt = '${{ secrets.ADDTEXT}}'
	deptid = '${{ secrets.DEPTID}}'
	userid = '${{ secrets.USERID}}'
	strnum = '${{ secrets.STUNUM}}'
	username = '${{ secrets.USERNAME}}'
	phonenum = '${{ secrets.PHONENUM}}'
	emergency = '${{ secrets.EMERGENCY}}'
	emergencyphone = '${{ secrets.EMERGENCYPHONE}}'
	
	do
	python3 17wanxiao.py <<EOF
	${text}
	${address}
	${addtxt}
	${deptid}
	${strnum}
	${username}
	${phonenum}
	${emergency}
	${emergencyphone}
	EOF
	done
