name: 17wanxiaoCheckin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
<<<<<<< HEAD
    - cron: 0 22 * * *
=======
    - cron: 0 5,22 * * *
>>>>>>> d407923a345feadb565e91e2cd08bc3ed9d574a2
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        python3 17wanxiao.py
